blueprint:
  name: Advanced Motion Lights
  description: >
    Motion-activated lights with Adaptive Lighting integration. Supports day/night lights,
    optional night mode sensor, optional blocking entity, and configurable timeout.
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      description: "Select the motion sensor that will trigger the automation."
      selector:
        entity:
          domain: binary_sensor

    main_lights:
      name: Main/Day Lights
      description: "Lights to turn on during normal/day mode."
      selector:
        target:
          entity:
            domain: light

    night_lights:
      name: Night Mode Lights (Optional)
      description: "Lights to turn on in night mode (if night mode sensor is configured)."
      selector:
        target:
          entity:
            domain: light
      default: []

    timeout:
      name: Timeout (seconds)
      description: >
        Number of seconds to wait after motion is cleared before turning lights off.
        If motion is detected again during this time, the countdown resets.
      default: 120
      selector:
        number:
          min: 1
          max: 3600
          unit_of_measurement: seconds
          mode: box

    block_entity:
      name: Blocking Entity (Optional)
      description: >
        If defined, the lights won't turn on when this entity is in a blocking state (e.g. 'on').
        For example, you can use a sleep mode switch. Leave empty to ignore.
      selector:
        entity: {}
      default: ""

    night_mode_entity:
      name: Night Mode Entity (Optional)
      description: >
        If defined, when this entity is 'on', the blueprint will use "Night Mode Lights".
        Otherwise, main lights will be used. Brightness is handled by Adaptive Lighting.
      selector:
        entity: {}
      default: ""

mode: restart
max_exceeded: silent

#############################################################
# 1) Trigger: When motion_sensor goes from off -> on
#############################################################
trigger:
  - platform: state
    entity_id: !input motion_sensor
    from: "off"
    to: "on"

#############################################################
# 2) Variables: Make the input references easier to use
#############################################################
variables:
  motion_sensor: !input motion_sensor
  main_lights: !input main_lights
  night_lights: !input night_lights
  timeout: !input timeout
  block_entity: !input block_entity
  night_mode_entity: !input night_mode_entity

#############################################################
# 3) Condition: Check the blocking entity if it’s set
#############################################################
condition:
  - condition: template
    value_template: >
      {{ block_entity == '' or not is_state(block_entity, 'on') }}

#############################################################
# 4) Action Steps
#############################################################
action:
  ###########################################################
  # Step A: Turn on the appropriate lights
  ###########################################################
  - choose:
      # If night_mode_entity is defined AND is on, use night_lights
      - conditions:
          - condition: template
            value_template: >
              {% if night_mode_entity != '' %}
                {{ is_state(night_mode_entity, 'on') }}
              {% else %}
                false
              {% endif %}
        sequence:
          - service: light.turn_on
            target: "{{ night_lights }}"
    # Default: use main_lights
    default:
      - service: light.turn_on
        target: "{{ main_lights }}"

  ###########################################################
  # Step B: Wait for motion to clear for the specified duration
  ###########################################################
  - wait_for_trigger:
      - platform: state
        entity_id: !input motion_sensor
        from: "on"
        to: "off"
        for:
          seconds: "{{ timeout }}"

  ###########################################################
  # Step C: Turn off lights (only if motion is still clear)
  ###########################################################
  - condition: state
    entity_id: !input motion_sensor
    state: "off"

  ###########################################################
  # Step D: Turn off all involved lights
  ###########################################################
  - service: light.turn_off
    target: "{{ main_lights }}"
  - service: light.turn_off
    target: "{{ night_lights }}"
